/**
 * Local Filesystem Storage Provider
 *
 * Stores uploaded files on the server's local disk under the Next.js `public/`
 * directory, so they are served statically at `/<key>` (e.g.
 * `/uploads/2025/07/...`). Next's static file handler gives us content-type
 * detection, caching headers and HTTP range requests (video seeking) for free.
 *
 * Intended for single-server / self-hosted deployments that don't want to run
 * an external object store. Not suitable for serverless/read-only filesystems.
 */

import { promises as fs } from "fs";
import path from "path";
import {
  StorageConfig,
  StorageService,
  UploadOptions,
  UploadResult,
  PresignedUrlResult,
  DeleteResult,
  ListFilesOptions,
  ListFilesResult,
  StorageObject,
} from "../types";
import { generateStorageKey } from "../key";

export class LocalStorageProvider implements StorageService {
  private config: StorageConfig;
  private baseDir: string;

  constructor(config: StorageConfig) {
    this.config = config;
    // Files live under the app's public/ dir so Next serves them statically.
    this.baseDir = path.join(process.cwd(), "public");
  }

  /**
   * Resolve a storage key to an absolute path inside baseDir, guarding against
   * path traversal (keys are generated by us, but deletion accepts a key from
   * the DB, so we defend in depth).
   */
  private resolvePath(key: string): string {
    const normalizedKey = key.replace(/^\/+/, "");
    const fullPath = path.resolve(this.baseDir, normalizedKey);
    const baseResolved = path.resolve(this.baseDir);
    if (
      fullPath !== baseResolved &&
      !fullPath.startsWith(baseResolved + path.sep)
    ) {
      throw new Error("Invalid storage key: path traversal detected");
    }
    return fullPath;
  }

  /**
   * Get public URL for a key. Always a same-site relative URL so Next treats
   * it as a local image (no remote-domain config needed) and the URL stays
   * valid on any host. publicUrl is an R2/S3-only concept and is intentionally
   * ignored here.
   */
  getPublicUrl(key: string): string {
    const normalizedKey = key.replace(/^\/+/, "");
    return `/${normalizedKey}`;
  }

  /**
   * Presigned direct uploads don't apply to local disk — callers should use the
   * server-side upload endpoint (/api/upload) instead.
   */
  async getPresignedUploadUrl(): Promise<PresignedUrlResult> {
    throw new Error(
      "Presigned uploads are not supported for local storage. Use direct upload instead.",
    );
  }

  /**
   * Upload file directly (server-side)
   */
  async uploadFile(
    file: Buffer,
    options: UploadOptions,
  ): Promise<UploadResult> {
    const key = generateStorageKey(this.config.pathPrefix, options);
    const fullPath = this.resolvePath(key);

    await fs.mkdir(path.dirname(fullPath), { recursive: true });
    await fs.writeFile(fullPath, file);

    return {
      success: true,
      key,
      url: this.getPublicUrl(key),
      size: options.fileSize,
      contentType: options.contentType,
    };
  }

  /**
   * Delete a file (idempotent — a missing file is treated as success)
   */
  async deleteFile(key: string): Promise<DeleteResult> {
    try {
      const fullPath = this.resolvePath(key);
      await fs.unlink(fullPath);
    } catch (error: unknown) {
      const code = (error as NodeJS.ErrnoException)?.code;
      if (code !== "ENOENT") throw error;
    }

    return {
      success: true,
      key,
    };
  }

  /**
   * List uploaded files under the path prefix, newest first. The cursor is a
   * plain offset into the sorted listing — re-walking the directory per page
   * is fine at admin-UI scale.
   */
  async listFiles(options: ListFilesOptions = {}): Promise<ListFilesResult> {
    const limit = Math.min(Math.max(options.limit ?? 50, 1), 200);
    const offset = Math.max(parseInt(options.cursor ?? "0", 10) || 0, 0);

    const prefix = (this.config.pathPrefix || "uploads/").replace(/^\/+/, "");
    const baseDir = this.resolvePath(prefix);

    const entries: { key: string; size: number; mtimeMs: number }[] = [];
    const walk = async (dir: string): Promise<void> => {
      let dirents;
      try {
        dirents = await fs.readdir(dir, { withFileTypes: true });
      } catch (error: unknown) {
        if ((error as NodeJS.ErrnoException)?.code === "ENOENT") return;
        throw error;
      }
      for (const dirent of dirents) {
        const fullPath = path.join(dir, dirent.name);
        if (dirent.isDirectory()) {
          await walk(fullPath);
        } else if (dirent.isFile() && !dirent.name.startsWith(".")) {
          const stat = await fs.stat(fullPath);
          entries.push({
            key: path.relative(this.baseDir, fullPath).split(path.sep).join("/"),
            size: stat.size,
            mtimeMs: stat.mtimeMs,
          });
        }
      }
    };
    await walk(baseDir);

    entries.sort((a, b) => b.mtimeMs - a.mtimeMs);

    const page = entries.slice(offset, offset + limit);
    const files: StorageObject[] = page.map((entry) => ({
      key: entry.key,
      url: this.getPublicUrl(entry.key),
      size: entry.size,
      lastModified: new Date(entry.mtimeMs).toISOString(),
    }));

    return {
      success: true,
      files,
      nextCursor:
        offset + limit < entries.length ? String(offset + limit) : undefined,
    };
  }

  /**
   * Local files are always served same-site — the public URL is the
   * download URL.
   */
  async getDownloadUrl(key: string): Promise<string> {
    return this.getPublicUrl(key);
  }

  /**
   * Test storage connection by verifying the target folder is writable.
   */
  async testConnection(): Promise<{ success: boolean; message: string }> {
    try {
      const prefix = (this.config.pathPrefix || "uploads/").replace(/^\/+/, "");
      const dir = path.resolve(this.baseDir, prefix);
      await fs.mkdir(dir, { recursive: true });

      const probe = path.join(dir, `.write-test-${Date.now()}`);
      await fs.writeFile(probe, "ok");
      await fs.unlink(probe).catch(() => null);

      return {
        success: true,
        message: "Local storage is writable",
      };
    } catch (error: unknown) {
      const message =
        error instanceof Error ? error.message : "unknown error";
      return {
        success: false,
        message: `Local storage is not writable: ${message}`,
      };
    }
  }
}
